# From https://docs.readthedocs.com/platform/stable/build-customization.html#install-dependencies-with-pixi

version: 2

# Read more at https://docs.readthedocs.com/platform/latest/config-file/v2.html#build
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    create_environment:
      - asdf plugin add pixi
      - asdf install pixi latest
      - asdf global pixi latest
    install:
      # assuming you have an environment called "docs"
      - pixi install -e rtd
    build:
      html:
        - pixi run --environment rtd rtd